name: Deploy to x Server

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH Key for Deploy

        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          target: ${{ secrets.REMOTE_PATH }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}

          script: rsync -avz --delete lp-demo/dist/ /home/solosoprani/solosoprani2002.com/public_html/lp
